CREATE DATABASE nodejs;

use nodejs;

CREATE TABLE
  estudiantes (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_APELLIDO VARCHAR(255),
    CORREO VARCHAR(255),
    CURSO VARCHAR(100),
    DNI VARCHAR(20),
    CELULAR VARCHAR(20),
    DIRECCION VARCHAR(255),
    FECHA_REGISTRO DATE
  );

SELECT
  *
FROM
  estudiantes;